name: Noël
favicon: null
layout_spectrum: 0.973806302761659
typography_spectrum: 0.044115563156083226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.30568576883524656
  lightness: 0.44054346065968275
  saturation: 0.47986058541573584
  rhythmicContrast: 0.11627163761295378
purpose: []
