name: Noël
favicon: null
layout_spectrum: 1
typography_spectrum: 0.044115563156083226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff4ca'
    - '#060a12'
    - '#00c1b0'
    - '#12587c'
    - '#a1af8f'
  brandStrength: 0.5
  lightness: 0.44054346065968275
  saturation: 0.47986058541573584
  rhythmicContrast: 0.11627163761295378
purpose: []
